### ISSUE TITLE
Refactor `/code_to_amr`

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#54]
## Current state

Previously, `Code` in TDS was just a single file per `Code` object which had a `filename`. This file associated with the `Code` object is fetched in the [`code_to_amr`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/operations.py#L539) worker operation with the assumption being that the file contains only core model dynamics. This is then sent to SKEMA's `/workflows/code/snippets-to-pn-amr` endpoint.

## Changes needed

Now, `Code` in TDS represents a collection of files: a repo. This is already implemented in [TDS's PR #328](https://github.com/DARPA-ASKEM/data-service/pull/328). `Code` now has a set of `files` each of which are stored to S3. Some of these files will have `dynamics` blocks. We should update the `/code_to_amr` endpoint to look at the `files`, identify those which have `dynamics`, download those files, extract the lines delineated in `dynamics.block` and send only those to SKEMA. If no `dynamics` are found for any `files` we should return an error.

**Additionally**, we should add a flag on the endpoint called `dynamics_only`. If `dynamics_only` is set to `False` (the default) the whole `Code` repo is zipped and sent to SKEMA's [`/codebase-to-pn-amr`](https://api.askem.lum.ai/docs#/workflows/repo_to_pn_amr_workflows_code_codebase_to_pn_amr_post). 

If it is set to `True` we only send the dynamics and send it to SKEMA's [`/snippets-to-pn-amr`](https://api.askem.lum.ai/docs#/workflows/code_snippets_to_pn_amr_workflows_code_snippets_to_pn_amr_post).

We'll use the same `worker` function for both and both will be invoked via the `/code_to_amr` endpoint. However each will be tested separately so that we can have 2 tests appear on the Integration Dashboard. The tests can be called `Code Dynamics to AMR` and `Code Repo to AMR`.

## TODO List

**Code Dynamics to AMR**
- [x] Generate test code "package" with corresponding test files in `tests/scenarios/basic`. We can take the existing [`code.py`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/code.py) file and put it into a directory called `code`, add a commented out description to the top and some `print` statements to the bottom so that only the key function `sir` is our dynamics. We should add a 2nd file such as `README.txt`. We should add a file in this directory called `dynamics.json` which indicates the files/blocks for generating the `dynamics`.
  - > Note: the new directory at `scenarios/basic/code` will have two files: `code.py` and `README.txt` to behave like a real repo with multiple files, even though only `code.py` will have dynamics.
- [x] Stub out test code in `test_e2e.py` which takes in the new test `code` package, mock creates it in TDS, and uses the `file_storage` to store it's various files. Ensure that at least one file has real `dynamics`; this can be accomplished by expanding the [`code.py`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/code.py) to have some other things in it, but just the `sir()` function are the dynamics block
- [x] update [`get_code_from_tds`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/utils.py#L192) to obtain all relevant files which contain dynamics. 
- [x] [Generate the code snippet array](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/operations.py#L547C10-L547C10) for passage to SKEMA. See [their example](https://api.askem.lum.ai/docs#/workflows/code_snippets_to_pn_amr_workflows_code_snippets_to_pn_amr_post); it appears that dynamics sections from multiple files can be appended to the same array. **SEE NOTE BELOW**
- [x] Add graceful failure for case when no `dynamics` are found
- [ ] Ensure that test in `test_e2e.py` works as expected

**Code Repo to AMR**
- [x] Add second test for sending an entire code repo to SKEMA's [`/codebase-to-pn-amr`](https://api.askem.lum.ai/docs#/workflows/repo_to_pn_amr_workflows_code_codebase_to_pn_amr_post)
- [x] Update worker task to handle sending the whole zip file
- [x] Add flag on API endpoint for `dynamics_only`
- [ ] Ensure test works as expected

> Note: since it's possible that `dynamics` are found in multiple code blocks _within_ the same file, we should discuss making the `dynamics.block` an `array` not a `string`
